name: Feature Request
description: Foresl친 en ny funksjon
title: "[Feature] 游"
labels: [feature]
assignees: []

body:
  - type: input
    id: feature-title
    attributes:
      label: Kort tittel p친 funksjonen
      placeholder: F.eks. "Legg til st칮tte for m칮rk modus"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beskrivelse av funksjonen
      description: Forklar kort hva funksjonen gj칮r og hvorfor den er nyttig.
      placeholder: F.eks. "Brukeren skal kunne bytte til m칮rk modus i brukerinnstillingene."
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: Deloppgaver (valgfritt)
      description: Skriv inn eventuelle steg som m친 til for 친 gjennomf칮re funksjonen. Du kan bruke sjekkbokser med `- [ ]`.
      placeholder: |
        - [ ] Legg til knapp i UI
        - [ ] Implementer tema-logikk
        - [ ] Lagre valg i brukerinnstillinger
    validations:
      required: false
